name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        options: >-
          --health-cmd="pg_isready -U user -d mydb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_pgsql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Prepare environment
        run: |
          echo "DATABASE_URL=postgresql://user:mypassword@localhost:5432/mydb" > .env

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -U user -d mydb; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 3
          done
          echo "Postgres not ready!"
          exit 1

      - name: Run migrations (if needed)
        run: |
          if [ -f ./bin/console ]; then
            php ./bin/console migrations:migrate --no-interaction
          fi

      - name: Run linter (PHP_CodeSniffer)
        run: vendor/bin/phpcs --standard=PSR12 src/

      - name: Run tests via make
        run: make test
